base: base.yaml
checkpoint:
  resume: false
  resume_path: ''
  save_best: true
  save_dir: ./checkpoints
  save_freq: 10
  save_last: true
data:
  batch_size: 8
  dataset_path: ./data
  normalization:
    mean:
    - 0.4781
    - 0.4458
    - 0.3957
    std:
    - 0.2626
    - 0.2572
    - 0.2653
  num_workers: 1
  shuffle: true
  validation_split: 0.2
device: cuda
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
model:
  block_attention: true
  channel_attention: true
  compression: 0.5
  dilatation: 1
  dropout_dblock: 0.0
  dropout_p: 0.2
  dropout_transition: 0.1
  growth_rate: 32
  in_channels: 3
  input_size: 224
  name: DenseNet121
  num_classes: 37
  pretrained: false
  spatial_attention: true
  trans_attention: false
  use_separable: false
output:
  log_dir: ./logs
  tensorboard: true
project:
  name: oxford III pet
  version: '1.0'
seed: 42
training:
  epochs: 150
  gamma: 0.1
  learning_rate: 0.0001
  momentum: false
  optimizer: adam
  scheduler: false
  step_size: 30
  weight_decay: 0.001
