model:
  name: "DenseNet121"
  checkpoint_path: "./checkpoints/DenseNet121_gr32_ep200_lr0.0001_bs8_20251005_134020/best_model.pth"  # ou last_epoch.pth
  num_classes: 37
  input_size: 224
  in_channels: 3
  growth_rate: 32
  compression: 0.5
  pretrained: false
  use_separable: false
  dropout_p: 0.2
  dropout_transition: 0.1
  dropout_dblock: 0.0
  channel_attention: false
  spatial_attention: true
  block_attention: true
  trans_attention: false  # opções: "channel", "spatial", None
  global_attention: false
data:
  dataset_path: "./data"
  dataset:
    type: "OxfordPetDataset"
  batch_size: 32
  shuffle: false
  num_workers: 1
  normalization:
    mean: [0.4781, 0.4458, 0.3957]
    std: [0.2626, 0.2572, 0.2653]

evaluation:
  output_dir: "./results"
  metrics: ["accuracy", "precision", "recall", "f1"]

device: "cuda"
