model:
  name: "DenseNet121"
  checkpoint_path: "./checkpoints3/DenseNet121_gr32_ep60_lr0.0001_bs40_20250910_193912/best_model.pth"  # ou last_epoch.pth
  num_classes: 37
  input_size: 224
  in_channels: 3
  growth_rate: 32
  compression: 0.5
  pretrained: false

data:
  dataset_path: "./data"
  dataset:
    type: "OxfordPetDataset"
  batch_size: 32
  shuffle: false
  num_workers: 1

evaluation:
  output_dir: "./results"
  metrics: ["accuracy", "precision", "recall", "f1"]

device: "cuda"
