# Configurações de treino
base: "base.yaml"

data:
  dataset_path: "./data"
  batch_size: 8
  shuffle: true
  num_workers: 1
  validation_split: 0.2
  normalization:
   mean: [0.4781, 0.4458, 0.3957]
   std: [0.2626, 0.2572, 0.2653]

model:
  name: "DenseNet121"
  input_size: 224
  num_classes: 37
  in_channels: 3
  growth_rate: 32
  compression: 0.5
  pretrained: false
  use_separable: false
  dilatation: 1
  dropout_p: 0.2
  dropout_dblock: 0.0
  dropout_transition: 0.1
  channel_attention: true
  spatial_attention: true
  block_attention: true
  trans_attention: true   # opções: "channel", "spatial", None
  global_attention: false


training:
  epochs: 150
  learning_rate: 0.0001
  weight_decay: 0.001
  momentum: false
  optimizer: "adam"
  scheduler: False
  step_size: 30
  gamma: 0.1

checkpoint:
  save_dir: "./checkpoints"
  save_freq: 10
  save_best: true
  save_last: true
  resume: false
  resume_path: ""

output:
  log_dir: "./logs"
  tensorboard: true
